apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-  

commonLabels:
  variant: stage

commonAnnotations:
  stage: stage
resources:
- ../../base

patchesStrategicMerge:
  - route.yaml
