apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- myconfigmap.yaml
- mysecrets.yaml
#- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- route.yaml
#The configMapGenerator and secretGenerator did not work inexplicably due to the changed name not getting reflected in Deployment.yaml, and hence, for now, I am commenting below and instead using myconfigmap.yaml and mysecrets.yaml
#configMapGenerator:
#- literals:
#  - MYSQL_HOSTNAME=mysql
#  name: my-config
#files:
#- ./connection.properties
#secretGenerator:
#- literals:
#  - MYSQLUSER=root
#  - MYSQLPASSWORD=p@ssword
#  name: my-creds
labels:
- includeSelectors: true
  pairs:
    org: bankofantarc.com
