apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: my-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: my-trigger
      bindings:
        - ref: my-binding
      template:
        ref: my-trigger-template

