apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-only
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
#Added the below workspace item for dockerconfig auth
  - name: maven-settings
    emptyDir: {}
  params:
  - name: repo-url
    value: https://github.com/srranjan/bankofantarc
