apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-only
spec:
  description: | 
    This pipeline clones a git repo, that is all it does.
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  workspaces:
  - name: shared-data
# Below for docker credential added
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
