apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
#Added the below workspace item for dockerconfig auth
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: maven-settings
#    configMap:
#        name: custom-maven-settings
    emptyDir: {}
  params:
  - name: repo-url
    value: https://github.com/srranjan/bankofantarc
# Added image-reference below
  - name: image-reference
    value: index.docker.io/srranjan/reactsvccrud:latest
