apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-  

commonLabels:
  variant: dev

commonAnnotations:
  stage: dev
resources:
- ../../base

patchesStrategicMerge:
  - route.yaml
