#apiVersion: gateway.networking.k8s.io/v1beta1
#https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/
apiVersion: gateway.networking.k8s.io/v1
#Upgrading to latest
kind: HTTPRoute
metadata:
  name: myrouter
spec:
  parentRefs:
  - name: common-gateway
  hostnames: ["bankofantarc.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /backsvc/clients
    backendRefs:
    - name: reactsvc
      port: 9095
  - matches:
    - path:
        type: PathPrefix
        value: /backsvc/version
    backendRefs:
    - name: reactsvc
      port: 9095

