apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
# choose one of username/password or auth token
# echo -n "admin" | base64
# echo -n "op5VFu80QVBNr0PE" | base64
  ARGOCD_USERNAME: YWRtaW4=
  ARGOCD_PASSWORD: b3A1VkZ1ODBRVkJOcjBQRQ==
#  ARGOCD_AUTH_TOKEN: <token>
