apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactsvc
  labels:
    app: reactsvc
spec:
  selector:
    matchLabels:
      app: reactsvc
  template:
    metadata:
      labels:
        app: reactsvc
    spec:
      containers:
      - name: reactsvc-container
        image: docker.io/srranjan007/reactsvcimg
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: reactsvc-service
spec:
  selector:
    app: reactsvc
  ports:
  - protocol: TCP
    port: 9091
---
apiVersion: v1
kind: Route
metadata:
  name: reactsvc-route
spec:
  to:
    kind: Service
    name: reactsvc-service
