apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactsvc
  labels:
    app: reactsvc
spec:
  selector:
    matchLabels:
      app: reactsvc
  template:
    metadata:
      labels:
        app: reactsvc
    spec:
      serviceAccountName: mysvcs-reactsvc
      containers:
      - name: reactsvc
        image: srranjan007/reactsvcimg2
#The above for local kind repos, the below the general public one
#      	image: docker.io/srranjan007/reactsvcimg2
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 9095
        env:
         - name: MYSQL_HOSTNAME
           valueFrom:
              configMapKeyRef:
                name: my-config
                key: MYSQL_HOSTNAME
         - name: MYSQLUSER
           valueFrom:
              secretKeyRef:
                name: my-creds
                key: MYSQLUSER
         - name: MYSQLPASSWORD
           valueFrom:
              secretKeyRef:
                name: my-creds
                key: MYSQLPASSWORD
status: {}
