apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMzSnlZVzVxWVc0NmJXRmhibWRoYm1vPSIKCQl9Cgl9Cn0=
