apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocdapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: corecrud
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/srranjan/bankofantarc'
    path: k8/kustomize/base
    targetRevision: main
#    helm: #Not using helm presently
#     valueFiles:
#        - values.yaml
#  sources: []
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: true
